<?php
/**
 * Giuseppe Morelli
 *
 * @package     gmdotnet/default/template/catalogsearch
 * @copyright   Copyright (c) 2016 Giuseppe Morelli (http://www.giuseppemorelli.net)
 */
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>
<div class="row">
    <div class="col-md-3 col-xs-1">&nbsp;</div>
    <div class="col-md-6 col-xs-10 text-center">
        <div class="row">
            <form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
                <div class="col-xs-12">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <label for="search"><?php echo $this->__('Search:') ?></label>
                        </span>
                        <input type="text" class="form-control input-text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" id="search" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>">
                        <span class="input-group-btn">
                            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Search')) ?>" class="btn btn-default"><span><span><?php echo $this->__('Search') ?></span></span></button>
                        </span>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                </div>
            </form>
            <script type="text/javascript">
                //<![CDATA[
                var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Search entire store here...')) ?>');
                searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
                //]]>
            </script>
        </div>
    </div>
    <div class="col-md-3 col-xs-1">&nbsp;</div>
</div>






