/*!
 * GMdotnet Gruntfile.js
 */

module.exports = function (grunt) {

    grunt.skinpath = '../htdocs/skin/frontend/gmdotnet/default/';

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        copy: {
            asset: {
                files: [
                    {
                        expand: true,
                        cwd: 'bower_components/bootstrap/dist/css/',
                        src: ['bootstrap.min.css'],
                        dest: '<%= grunt.skinpath %>css/',
                        filter: 'isFile'
                    },
                    {
                        expand: true,
                        cwd: 'bower_components/bootstrap/dist/fonts/',
                        src: ['*'],
                        dest: '<%= grunt.skinpath %>fonts/',
                        filter: 'isFile'
                    },
                    {
                        expand: true,
                        cwd: 'bower_components/bootstrap/dist/js/',
                        src: ['bootstrap.min.js'],
                        dest: '<%= grunt.skinpath %>js/',
                        filter: 'isFile'
                    },
                    {
                        expand: true,
                        cwd: 'bower_components/jquery/dist/',
                        src: ['jquery.min.js'],
                        dest: '<%= grunt.skinpath %>js/',
                        filter: 'isFile'
                    },
                    {
                        expand: true,
                        cwd: 'bower_components/font-awesome/fonts/',
                        src: ['*'],
                        dest: '<%= grunt.skinpath %>fonts/',
                        filter: 'isFile'
                    },
                    {
                        expand: true,
                        cwd: 'bower_components/font-awesome/css/',
                        src: ['font-awesome.min.css'],
                        dest: '<%= grunt.skinpath %>css/',
                        filter: 'isFile'
                    },
                    {
                        expand: true,
                        cwd: 'bower_components/malihu-custom-scrollbar-plugin/',
                        src: ['jquery.mCustomScrollbar.min.css'],
                        dest: '<%= grunt.skinpath %>css/',
                        filter: 'isFile'
                    },
                    {
                        expand: true,
                        cwd: 'bower_components/malihu-custom-scrollbar-plugin/',
                        src: ['jquery.mCustomScrollbar.concat.min.js'],
                        dest: '<%= grunt.skinpath %>js/',
                        filter: 'isFile'
                    },
                    {
                        expand: true,
                        cwd: 'bower_components/jquery-searcher/dist/',
                        src: ['jquery.searcher.min.js'],
                        dest: '<%= grunt.skinpath %>js/',
                        filter: 'isFile'
                    }
                ]
            }
        },
        cssmin: {
            options: {
                compatibility: 'ie8',
                keepSpecialComments: '*',
                advanced: false,
                banner: '/*! <%= pkg.name %> - v<%= pkg.version %> - ' +
                '<%= grunt.template.today("yyyy-mm-dd") %> This file is autogenerated! Please do not modify! */'
            },
            target: {
                files: {
                    '<%= grunt.skinpath %>css/styles.min.css': ['<%= grunt.skinpath %>css/styles.css']
                }
            }
        },
        uglify: {
            options: {
                banner: '/*! <%= pkg.name %> - v<%= pkg.version %> - ' +
                '<%= grunt.template.today("yyyy-mm-dd") %> This file is autogenerated! Please do not modify! */'
            },
            my_target: {
                files: {
                    '<%= grunt.skinpath %>js/jquery.scripts.min.js': ['<%= grunt.skinpath %>js/jquery.scripts.js'],
                    '<%= grunt.skinpath %>js/jquery.scripts.category.min.js': ['<%= grunt.skinpath %>js/jquery.scripts.category.js']
                }
            }
        },
        watch: {
            scripts: {
                files: ['<%= grunt.skinpath %>css/*.css', '<%= grunt.skinpath %>js/*.js'],
                tasks: ['default'],
                options: {
                    spawn:false,
                    event:['changed']
                }
            }
        }
    });

    // Load library
    require('load-grunt-tasks')(grunt, {scope: 'devDependencies'});

    // TASK
    grunt.registerTask('deploy', ['copy:asset']);
    grunt.registerTask('minify-css', ['cssmin']);
    grunt.registerTask('minify-js', ['uglify']);

    grunt.registerTask('default', ['copy:asset', 'minify-css', 'minify-js']);
};