<?php
/**
 * Giuseppe Morelli
 *
 * @package     gmdotnet/default/template/page/template
 * @copyright   Copyright (c) 2016 Giuseppe Morelli (http://www.giuseppemorelli.net)
 */
?>
<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>

<nav class="navbar navbar-default navbar-main toplinks" role="navigation">
    <div class="navbar-header">
        <a class="navbar-brand" href="#" data-toggle="collapse" data-target="#toplinks">
            <?php echo $this->__('Menu') ?>
        </a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#toplinks">
            <span class="sr-only"><?php echo $this->__('Toggle Navigation') ?></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <div id="toplinks" class="collapse navbar-collapse navbar-main-collapse">
        <?php $_links = $this->getLinks(); ?>
        <?php if(count($_links)>0): ?>
            <ul class="nav navbar-nav"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
                <?php foreach($_links as $_link): ?>
                    <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
                        <?php echo $_link->toHtml() ?>
                    <?php else: ?>
                        <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> role="presentation" class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
                    <?php endif;?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</nav>

